#!/usr/bin/env python3
"""Generate GitHub-native, 50-locale buyer-intent README directories."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
from typing import Any
import urllib.parse

from app_store_storefronts import (
    CAMPAIGN_TOKEN_RE,
    campaign_app_store_url,
    validated_app_store_url,
)
from official_locales import OFFICIAL_LOCALES
import publisher_intent_catalog as catalog


HERE = Path(__file__).resolve().parent
PAGES = Path(os.environ.get("GEO_PAGES", HERE / "pages"))
GENERATED_MARKER = (
    "<!-- Generated by gen_github_discovery_readmes.py; do not edit. -->"
)
QUERY_ORIGIN = "publisher_authored_editorially_localized"
GUIDE_HOST = "alice51849.github.io"
GUIDE_PREFIX = "/ios-app-guide/"
MCP_REPOSITORY_URL = "https://github.com/alice51849/lumi-mcp"
MCP_REGISTRY_URL = (
    "https://registry.modelcontextprotocol.io/v0.1/servers/"
    "io.github.alice51849%2Flumi-app-finder/versions/latest"
)
MCP_BUNDLE_URL = (
    "https://github.com/alice51849/lumi-mcp/releases/latest/download/"
    "lumi-app-finder.mcpb"
)
TEXT_FIELDS = (
    "app_key",
    "app_name",
    "app_store_id",
    "publisher_query",
    "decision_context",
    "purchase_model",
    "canonical_guide_url",
    "canonical_app_store_url",
    "app_store_url",
    "app_store_cta_label",
    "publisher_disclosure",
    "query_origin",
)


def _single_line(value: object, field: str) -> str:
    if (
        not isinstance(value, str)
        or not value.strip()
        or value != value.strip()
        or any(ord(char) < 32 for char in value)
    ):
        raise ValueError(f"Invalid GitHub discovery {field}")
    return value


def _validate_guide_url(value: str, locale: str) -> None:
    parsed = urllib.parse.urlsplit(value)
    expected_prefix = f"{GUIDE_PREFIX}{locale}/answers/"
    if (
        parsed.scheme != "https"
        or parsed.netloc != GUIDE_HOST
        or not parsed.path.startswith(expected_prefix)
        or not parsed.path.endswith(".html")
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError(
            f"Invalid GitHub discovery guide URL for {locale}: {value}"
        )


def validate_dataset(payload: dict[str, object]) -> list[dict[str, Any]]:
    records = payload.get("records")
    if (
        payload.get("app_count") != catalog.EXPECTED_APP_COUNT
        or payload.get("locale_count") != len(OFFICIAL_LOCALES)
        or payload.get("record_count") != catalog.EXPECTED_RECORD_COUNT
        or payload.get("locales") != list(OFFICIAL_LOCALES)
        or payload.get("query_origin") != QUERY_ORIGIN
        or payload.get("measured_search_volume") is not False
        or payload.get("is_ranking") is not False
        or not isinstance(records, list)
        or len(records) != catalog.EXPECTED_RECORD_COUNT
        or re.fullmatch(
            r"\d{4}-\d{2}-\d{2}",
            str(payload.get("dateModified") or ""),
        )
        is None
    ):
        raise ValueError("GitHub discovery source has invalid coverage metadata")

    pairs: set[tuple[str, str]] = set()
    app_ids: dict[str, str] = {}
    validated: list[dict[str, Any]] = []
    for raw in records:
        if not isinstance(raw, dict):
            raise ValueError("GitHub discovery source has a non-object record")
        missing = set(TEXT_FIELDS) - set(raw)
        if missing:
            raise ValueError(
                "GitHub discovery source record is missing "
                + ", ".join(sorted(missing))
            )
        record = dict(raw)
        for field in TEXT_FIELDS:
            record[field] = _single_line(record[field], field)
        locale = record.get("locale")
        if not isinstance(locale, str) or locale not in OFFICIAL_LOCALES:
            raise ValueError(f"Invalid GitHub discovery locale: {locale!r}")
        key = record["app_key"]
        app_id = record["app_store_id"]
        pair = (key, locale)
        if (
            not re.fullmatch(r"[a-z0-9]+", key)
            or not re.fullmatch(r"\d{9,12}", app_id)
            or pair in pairs
            or record["purchase_model"] not in catalog.PURCHASE_LABELS
            or record["query_origin"] != QUERY_ORIGIN
            or record.get("measured_search_volume") is not False
            or record.get("is_ranking") is not False
            or record.get("verified_live") is not True
            or re.search(
                r"https?://",
                f"{record['publisher_query']} {record['decision_context']}",
                flags=re.IGNORECASE,
            )
        ):
            raise ValueError(
                f"Invalid GitHub discovery record: {key}/{locale}"
            )
        previous_app_id = app_ids.setdefault(key, app_id)
        if previous_app_id != app_id:
            raise ValueError(f"App Store ID changed within catalog: {key}")
        canonical_store = f"https://apps.apple.com/app/id{app_id}"
        if record["canonical_app_store_url"] != canonical_store:
            raise ValueError(f"Wrong canonical App Store URL: {key}/{locale}")
        _validate_guide_url(record["canonical_guide_url"], locale)
        validated_app_store_url(record["app_store_url"], app_id)
        pairs.add(pair)
        validated.append(record)

    expected_pairs = {
        (key, locale)
        for key in app_ids
        for locale in OFFICIAL_LOCALES
    }
    if (
        len(app_ids) != catalog.EXPECTED_APP_COUNT
        or pairs != expected_pairs
    ):
        raise ValueError("GitHub discovery source does not cover every app/locale")
    return validated


def campaign_token(locale: str) -> str:
    token = f"iag_gh_{locale.replace('-', '_').lower()}"
    if CAMPAIGN_TOKEN_RE.fullmatch(token) is None:
        raise ValueError(f"Invalid GitHub README campaign token: {token}")
    return token


def github_store_url(record: dict[str, Any]) -> str:
    result = campaign_app_store_url(
        record["app_store_url"],
        campaign_token(record["locale"]),
    )
    validated_app_store_url(result, record["app_store_id"])
    return result


def _markdown_text(value: object) -> str:
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _markdown_link(label: object, url: str) -> str:
    if any(char in url for char in ("\r", "\n", " ", "(", ")")):
        raise ValueError(f"Unsafe Markdown URL: {url}")
    return f"[{_markdown_text(label)}]({url})"


def _locale_navigation(locale: str | None) -> str:
    links = []
    for option in OFFICIAL_LOCALES:
        if option == locale:
            links.append(f"**{option}**")
            continue
        target = (
            f"./{option}/"
            if locale is None
            else f"../{option}/"
        )
        links.append(f"[{option}]({target})")
    return " · ".join(links)


def _render_readme(
    locale: str,
    records: list[dict[str, Any]],
    ui: dict[str, str],
    *,
    root: bool,
    modified: str,
) -> str:
    ordered = sorted(
        records,
        key=lambda record: (
            record["app_name"].casefold(),
            record["app_key"],
        ),
    )
    if len(ordered) != catalog.EXPECTED_APP_COUNT:
        raise ValueError(f"Incomplete GitHub README records: {locale}")
    catalog_url = (
        f"{catalog.SITE}/data/{catalog.SLUG}.html"
        if root
        else f"{catalog.SITE}/{locale}/data/{catalog.SLUG}.html"
    )
    home_url = (
        f"{catalog.SITE}/index.html"
        if root
        else f"{catalog.SITE}/{locale}/index.html"
    )
    table = [
        "| "
        + " | ".join(
            _markdown_text(ui[field])
            for field in (
                "App",
                "Publisher query",
                "Decision context",
                "Purchase model",
                "Guide",
            )
        )
        + " | App Store |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for record in ordered:
        table.append(
            "| "
            + " | ".join(
                (
                    f"**{_markdown_text(record['app_name'])}**",
                    _markdown_text(record["publisher_query"]),
                    _markdown_text(record["decision_context"]),
                    _markdown_text(
                        ui[catalog.PURCHASE_LABELS[record["purchase_model"]]]
                    ),
                    _markdown_link(
                        ui["Guide"],
                        record["canonical_guide_url"],
                    ),
                    _markdown_link(
                        record["app_store_cta_label"],
                        github_store_url(record),
                    ),
                )
            )
            + " |"
        )

    navigation_locale = None if root else locale
    lines = [
        GENERATED_MARKER,
        "",
        f"# {_markdown_text(ui[catalog.NAME])}",
        "",
        _markdown_text(ui[catalog.DESCRIPTION]),
        "",
        _markdown_text(ui[catalog.LEAD]),
        "",
        f"**{_markdown_text(ui['Locale'])}:** "
        f"{_locale_navigation(navigation_locale)}",
        "",
        f"> **{_markdown_text(ui['First-party publisher catalog'])}**",
        ">",
        f"> {_markdown_text(ui[catalog.DISCLOSURE])}",
        ">",
        f"> {_markdown_text(ui[catalog.NON_MEASURED])}",
        "",
        f"## {_markdown_text(ui[catalog.NAME])} · MCP",
        "",
        _markdown_text(ui[catalog.DESCRIPTION]),
        "",
        " · ".join(
            (
                _markdown_link("MCP Registry", MCP_REGISTRY_URL),
                _markdown_link("GitHub", MCP_REPOSITORY_URL),
                _markdown_link("MCPB", MCP_BUNDLE_URL),
            )
        ),
        "",
        f"## {_markdown_text(ui['Methodology'])}",
        "",
        _markdown_text(ui[catalog.METHODOLOGY]),
        "",
        _markdown_text(ui["Alphabetical by app name — never a ranking."]),
        "",
        f"## {_markdown_text(ui['Records'])}",
        "",
        *table,
        "",
        f"## {_markdown_text(ui['Download the complete dataset'])}",
        "",
        _markdown_text(
            ui["JSON, JSONL and CSV contain the same 1,300 records."]
        ),
        "",
        " · ".join(
            (
                _markdown_link(
                    "JSON",
                    f"{catalog.SITE}/data/{catalog.SLUG}.json",
                ),
                _markdown_link(
                    "JSONL",
                    f"{catalog.SITE}/data/{catalog.SLUG}.jsonl",
                ),
                _markdown_link(
                    "CSV",
                    f"{catalog.SITE}/data/{catalog.SLUG}.csv",
                ),
                _markdown_link(
                    "MLCommons Croissant 1.1",
                    catalog.CROISSANT_URL,
                ),
            )
        ),
        "",
        "---",
        "",
        " · ".join(
            (
                _markdown_link(ui["Home"], home_url),
                _markdown_link(ui["Open data"], catalog_url),
                _markdown_link(ui["License"], catalog.LICENSE_URL),
            )
        ),
        "",
        f"{_markdown_text(ui['Updated'])}: {modified}",
        "",
        _markdown_text(
            ui[
                "CC BY 4.0 applies to the original catalog compilation; "
                "app names and App Store marks belong to their owners."
            ]
        ),
        "",
    ]
    return "\n".join(lines)


def _write_managed(path: Path, content: str) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing[:200]:
            raise ValueError(f"Refusing to overwrite unmanaged README: {path}")
    return catalog.write_text_if_changed(path, content)


def build(pages: Path = PAGES) -> tuple[Path, ...]:
    source_path = pages / "data" / f"{catalog.SLUG}.json"
    payload = json.loads(source_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("GitHub discovery source root must be an object")
    records = validate_dataset(payload)
    ui_i18n = {
        locale: catalog.dynamic_ui(mapping)
        for locale, mapping in catalog.load_ui_i18n().items()
    }
    by_locale = {
        locale: [
            record for record in records if record["locale"] == locale
        ]
        for locale in OFFICIAL_LOCALES
    }
    modified = str(payload["dateModified"])
    targets = {
        pages / "README.md": _render_readme(
            "en-US",
            by_locale["en-US"],
            ui_i18n["en-US"],
            root=True,
            modified=modified,
        ),
        **{
            pages / locale / "README.md": _render_readme(
                locale,
                by_locale[locale],
                ui_i18n[locale],
                root=False,
                modified=modified,
            )
            for locale in OFFICIAL_LOCALES
        },
    }
    changed = tuple(
        path
        for path, content in targets.items()
        if _write_managed(path, content)
    )
    expected_locale_paths = {
        pages / locale / "README.md" for locale in OFFICIAL_LOCALES
    }
    for path in pages.glob("*/README.md"):
        if (
            path not in expected_locale_paths
            and GENERATED_MARKER in path.read_text(encoding="utf-8")[:200]
        ):
            path.unlink()
            changed += (path,)
    print(
        "GITHUB_DISCOVERY_READMES "
        f"apps={catalog.EXPECTED_APP_COUNT} "
        f"locales={len(OFFICIAL_LOCALES)} files={len(targets)} "
        f"changed={len(changed)}",
        flush=True,
    )
    return changed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pages",
        type=Path,
        default=PAGES,
        help="Pages repository root.",
    )
    args = parser.parse_args()
    build(args.pages.resolve())


if __name__ == "__main__":
    main()
